services:
  konvertHR-saas-frontend:
    image: konverthr-saas-frontend
    container_name: konvertHR-saas-frontend-container
    env_file:
      # ENV FILE path 
      - "C:\\Users\\B A P S\\Downloads\\env.development.download"
    build:
      context: .
      args:
        PORT: ${PORT:-3001}
        
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    restart: always
    # scale: 3
