services:
  konvertHR-saas-frontend:
    image: konverthr-saas-frontend
    container_name: konvertHR-saas-frontend-container
    # env_file:
    #   - .env.development
    build: .
    ports:
      - "3000:3000"
    restart: always
    # scale: 3
